logging:
  level:
    ROOT: info
    az.kapitalbank.transaction: trace

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  liquibase:
    change-log: classpath:/liquibase/changelog-master.yaml

  main:
    banner-mode: log
  datasource:
    url: jdbc:postgresql://localhost:5432/customerdb
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 3
  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: full

application:
  client:
    customer:
      url: http://localhost:8081
